-- 1
CREATE OR REPLACE TEMPORARY TABLE TEMP_IMDB_TITLES_RATINGS AS
SELECT
	T.*
	, R.AVERAGERATING
	, R.NUMVOTES
FROM COURSES.SCH_CZECHITA.IMDB_TITLES2 AS T
INNER JOIN COURSES.SCH_CZECHITA.IMDB_RATINGS2 AS R
	ON T.TCONST = R.TCONST
;


-- 2 
CREATE OR REPLACE TEMPORARY TABLE TEMP_TITLETYPE_NEW AS
SELECT
	*
	, CASE
    	WHEN TITLETYPE IN ('movie', 'short', 'tvMovie', 'tvShort') THEN 'Movie'
    	WHEN TITLETYPE IN ('tvSeries', 'tvMiniSeries') THEN 'TV Show'
	END AS TITLETYPE_NEW
FROM TEMP_IMDB_TITLES_RATINGS
;


-- 3
CREATE OR REPLACE TABLE NETFLIX_IMDB AS
SELECT *
FROM TEMP_TITLETYPE_NEW
INNER JOIN COURSES.SCH_CZECHITA.NETFLIX_TITLES2
	ON PRIMARYTITLE = TITLE
	AND STARTYEAR = RELEASE_YEAR
	AND TITLETYPE_NEW = TYPE
;


-- 4
SELECT SHOW_ID, COUNT(*)
FROM NETFLIX_IMDB
GROUP BY SHOW_ID
HAVING COUNT(*) > 1
;
-- Duplicit (opakujicích se SHOW_ID) jsem našla celkem 6.
