-- 1. Vývoj po dnech v roce 2015 v zemích Iraq, Nigeria a Syria

SELECT
	COUNTRY_TXT AS COUNTRY
	, DATE_FROM_PARTS(IYEAR, IMONTH, IDAY) AS DATE
	, COUNT(EVENTID) AS TOTAL_ATTACKS
	, SUM(NKILL) - SUM(NKILLTER) AS TOTAL_VICTIMS
	, SUM(NKILLTER) AS DEAD_TERRORISTS
	, SUM(NWOUND) AS WOUNDED
FROM TEROR
WHERE
	IYEAR = 2015
	AND COUNTRY_TXT IN ('Iraq', 'Nigeria', 'Syria')  
GROUP BY COUNTRY_TXT, DATE
HAVING
	TOTAL_VICTIMS >= 8
	AND COUNT(EVENTID) >= 10
ORDER BY COUNTRY, DATE
;



-- 2. Vzdálenost útoků od Prahy

SELECT
	COUNT(EVENTID) AS TOTAL_ATTACKS
	, SUM(NKILL) - SUM(NKILLTER) AS TOTAL_VICTIMS
	, CASE
    	WHEN HAVERSINE(50.0755, 14.4378, LATITUDE, LONGITUDE) >= 1000 THEN '1000+ km'
    	WHEN HAVERSINE(50.0755, 14.4378, LATITUDE, LONGITUDE) >= 500 THEN '500-999 km'
    	WHEN HAVERSINE(50.0755, 14.4378, LATITUDE, LONGITUDE) >= 100 THEN '100-499 km'
    	WHEN HAVERSINE(50.0755, 14.4378, LATITUDE, LONGITUDE) >= 0 THEN '0-99 km'
    	ELSE 'Exact location unknown'
	END AS DIST_FROM_PRAGUE
FROM TEROR
WHERE IYEAR BETWEEN 2014 AND 2015
GROUP BY DIST_FROM_PRAGUE
ORDER BY TOTAL_ATTACKS DESC
;



-- 3. 15 útoků s největším počtem mrtvých ze zemí Iraq, Afghanistan, Pakistan, Nigeria

SELECT
	EVENTID
	, IYEAR
	, COUNTRY_TXT
	, CITY
	, ATTACKTYPE1_TXT
	, TARGTYPE1_TXT
	, GNAME
	, WEAPTYPE1_TXT
	, NKILL
FROM TEROR
WHERE
	COUNTRY_TXT IN ('Iraq', 'Afghanistan', 'Pakistan', 'Nigeria')
	AND (GNAME = 'Taliban' OR TARGTYPE1_TXT != 'Private Citizens & Property')
--	AND NKILL IS NOT NULL
ORDER BY NKILL DESC NULLS LAST
LIMIT 15
;